export type TableData = {
  id: string;
  amount: number;
  status: boolean;
  email: string;
  name: string;
};

const TABLE_DATA: TableData[] = [
  {
    id: "m5gr84i9",
    amount: 316,
    status: true,
    email: "ken99@example.com",
    name: "Ken",
  },
  {
    id: "3u1reuv4",
    amount: 242,
    status: true,
    email: "Abe45@example.com",
    name: "Abe",
  },
  {
    id: "derv1ws0",
    amount: 837,
    status: false,
    email: "Monserrat44@example.com",
    name: "Monserrat",
  },
  {
    id: "5kma53ae",
    amount: 874,
    status: true,
    email: "Silas22@example.com",
    name: "Silas",
  },
  {
    id: "bhqecj4p",
    amount: 721,
    status: false,
    email: "carmella@example.com",
    name: "Carmella",
  },
  {
    id: "x7k9d2pq",
    amount: 445,
    status: true,
    email: "sarah78@example.com",
    name: "Sarah",
  },
  {
    id: "n3m5v8yt",
    amount: 932,
    status: false,
    email: "james.doe@example.com",
    name: "James",
  },
  {
    id: "h4w2z9rx",
    amount: 553,
    status: true,
    email: "emma.smith@example.com",
    name: "Emma",
  },
  {
    id: "j6q8c5vn",
    amount: 678,
    status: false,
    email: "michael55@example.com",
    name: "Michael",
  },
  {
    id: "p7t4m2bk",
    amount: 389,
    status: true,
    email: "lisa.wong@example.com",
    name: "Lisa",
  },
  {
    id: "w9f5h3dl",
    amount: 764,
    status: true,
    email: "robert90@example.com",
    name: "Robert",
  },
  {
    id: "u2s8g4jm",
    amount: 291,
    status: false,
    email: "anna.lee@example.com",
    name: "Anna",
  },
  {
    id: "e6y4k7xp",
    amount: 847,
    status: true,
    email: "david.kim@example.com",
    name: "David",
  },
  {
    id: "l8b3n6qt",
    amount: 523,
    status: false,
    email: "rachel99@example.com",
    name: "Rachel",
  },
  {
    id: "i1r7v4cz",
    amount: 635,
    status: true,
    email: "thomas.park@example.com",
    name: "Thomas",
  },
  {
    id: "o5a9d2wm",
    amount: 456,
    status: false,
    email: "jessica88@example.com",
    name: "Jessica",
  },
  {
    id: "t4k6h8bn",
    amount: 789,
    status: true,
    email: "chris.lee@example.com",
    name: "Chris",
  },
  {
    id: "q2w9m5xz",
    amount: 912,
    status: false,
    email: "sophia.kim@example.com",
    name: "Sophia",
  },
  {
    id: "f7y3l1vp",
    amount: 345,
    status: true,
    email: "daniel.cho@example.com",
    name: "Daniel",
  },
  {
    id: "c8u4b6sk",
    amount: 567,
    status: false,
    email: "emily.wang@example.com",
    name: "Emily",
  },
  {
    id: "r9k2p7mz",
    amount: 623,
    status: true,
    email: "alex.park@example.com",
    name: "Alex",
  },
  {
    id: "v5h8n3wd",
    amount: 445,
    status: false,
    email: "jennifer.kim@example.com",
    name: "Jennifer",
  },
  {
    id: "b4x6j9lq",
    amount: 891,
    status: true,
    email: "william.lee@example.com",
    name: "William",
  },
  {
    id: "g7m2c5yt",
    amount: 334,
    status: false,
    email: "michelle.choi@example.com",
    name: "Michelle",
  },
  {
    id: "k3s8f4hp",
    amount: 778,
    status: true,
    email: "brian.jung@example.com",
    name: "Brian",
  },
  {
    id: "z6d9w2vn",
    amount: 556,
    status: false,
    email: "hannah.song@example.com",
    name: "Hannah",
  },
  {
    id: "a1e4x7ut",
    amount: 912,
    status: true,
    email: "kevin.yoon@example.com",
    name: "Kevin",
  },
  {
    id: "m8b5r2kq",
    amount: 445,
    status: false,
    email: "grace.park@example.com",
    name: "Grace",
  },
  {
    id: "y9n6h3wl",
    amount: 667,
    status: true,
    email: "justin.cho@example.com",
    name: "Justin",
  },
  {
    id: "d2t7p4vx",
    amount: 889,
    status: false,
    email: "stephanie.lee@example.com",
    name: "Stephanie",
  },
  {
    id: "l5c8m1bz",
    amount: 543,
    status: true,
    email: "ryan.kim@example.com",
    name: "Ryan",
  },
  {
    id: "w4f7j2sq",
    amount: 776,
    status: false,
    email: "natalie.park@example.com",
    name: "Natalie",
  },
  {
    id: "h1k4n7xm",
    amount: 432,
    status: true,
    email: "eric.jung@example.com",
    name: "Eric",
  },
  {
    id: "s8v5b2pd",
    amount: 654,
    status: false,
    email: "olivia.kim@example.com",
    name: "Olivia",
  },
  {
    id: "u3g6t9ry",
    amount: 887,
    status: true,
    email: "andrew.lee@example.com",
    name: "Andrew",
  },
  {
    id: "e7x2c5wq",
    amount: 543,
    status: false,
    email: "sophia.choi@example.com",
    name: "Sophia",
  },
  {
    id: "p4m9h6vz",
    amount: 765,
    status: true,
    email: "brandon.park@example.com",
    name: "Brandon",
  },
  {
    id: "i1b4f7nt",
    amount: 432,
    status: false,
    email: "isabella.song@example.com",
    name: "Isabella",
  },
  {
    id: "t8l5k2wd",
    amount: 654,
    status: true,
    email: "matthew.jung@example.com",
    name: "Matthew",
  },
  {
    id: "c3r6y9sq",
    amount: 876,
    status: false,
    email: "victoria.lee@example.com",
    name: "Victoria",
  },
  {
    id: "x7h2n5mp",
    amount: 543,
    status: true,
    email: "daniel.park@example.com",
    name: "Daniel",
  },
  {
    id: "q4v9b2kz",
    amount: 765,
    status: false,
    email: "emma.choi@example.com",
    name: "Emma",
  },
  {
    id: "o1g4t7wy",
    amount: 432,
    status: true,
    email: "christopher.kim@example.com",
    name: "Christopher",
  },
  {
    id: "j8m5f2hd",
    amount: 654,
    status: false,
    email: "ava.jung@example.com",
    name: "Ava",
  },
  {
    id: "n3x6c9pq",
    amount: 887,
    status: true,
    email: "michael.song@example.com",
    name: "Michael",
  },
  {
    id: "b7k2r5vt",
    amount: 543,
    status: false,
    email: "madison.park@example.com",
    name: "Madison",
  },
  {
    id: "f4h9l2mz",
    amount: 765,
    status: true,
    email: "ethan.lee@example.com",
    name: "Ethan",
  },
  {
    id: "w1t4y7sq",
    amount: 432,
    status: false,
    email: "chloe.kim@example.com",
    name: "Chloe",
  },
  {
    id: "d8n5b2xp",
    amount: 654,
    status: true,
    email: "jacob.choi@example.com",
    name: "Jacob",
  },
  {
    id: "m3g6v9wd",
    amount: 876,
    status: false,
    email: "lily.jung@example.com",
    name: "Lily",
  },
];

export default TABLE_DATA;
